mineral_catalog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.redirect_to_minerals)
]

urlpatterns += staticfiles_urlpatterns()

minerals/urls.py
from django.conf.urls import url

from . import views


urlpatterns = (
    url(r'^$', views.mineral_list, name='list'),
    url(r'(?P<pk>\d+)/$', views.mineral_detail, name='detail')
)

minerals/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(max_length=100)
    image_filename = models.CharField(max_length=200, null=True)
    image_caption = models.CharField(max_length=200, null=True)
    group = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=200, null=True)
    formula = models.CharField(max_length=200, null=True)
    strunz_classification = models.CharField(max_length=200, null=True)
    crystal_system = models.CharField(max_length=200, null=True)
    mohs_scale_hardness = models.CharField(max_length=200, null=True)
    luster = models.CharField(max_length=200, null=True)
    color = models.CharField(max_length=200, null=True)
    specific_gravity = models.CharField(max_length=200, null=True)
    cleavage = models.CharField(max_length=200, null=True)
    streak = models.CharField(max_length=200, null=True)
    diaphaneity = models.CharField(max_length=200, null=True)
    optical_properties = models.CharField(max_length=200, null=True)
    refractive_index = models.CharField(max_length=200, null=True)
    crystal_habit = models.CharField(max_length=200, null=True)
    crystal_symmetry = models.CharField(max_length=200, null=True)
    unit_cell = models.CharField(max_length=200, null=True)

    class Meta:
        ordering = ['name', ]

    def __str__(self):
        return self.name

mineral_catalog/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import HttpResponseRedirect


def redirect_to_minerals(request):
    return HttpResponseRedirect(reverse('minerals:list'))

minerals/views.py
from django.shortcuts import get_object_or_404, render
from django.forms.models import model_to_dict
from collections import OrderedDict
from random import randint

from .models import Mineral


def rand_mineral():
    rand_pk = randint(1, Mineral.objects.all().count())
    return rand_pk


def mineral_list(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/index.html', {
        'minerals': minerals,
        'rand_pk': rand_mineral()}
    )


def mineral_detail(request, pk):
    mineral = model_to_dict(get_object_or_404(Mineral, pk=pk))

    header = OrderedDict()
    if 'id' in mineral:
        header.update({'id': mineral.pop('id')})
    if 'name' in mineral:
        header.update({'name': mineral.pop('name')})
    if 'image_filename' in mineral:
        header.update({'image_filename': mineral.pop('image_filename')})
    if 'image_caption' in mineral:
        header.update({'image_caption': mineral.pop('image_caption')})

    body = OrderedDict()
    if 'group' in mineral:
        body.update({'group': mineral.pop('group')})
    if 'category' in mineral:
        body.update({'category': mineral.pop('category')})
    if 'formula' in mineral:
        body.update({'formula': mineral.pop('formula')})
    if 'strunz_classification' in mineral:
        body.update({
            'strunz_classification': mineral.pop('strunz_classification')})
    if 'crystal_system' in mineral:
        body.update({'crystal_system': mineral.pop('crystal_system')})
    if 'mohs_scale_hardness' in mineral:
        body.update({
            'mohs_scale_hardness': mineral.pop('mohs_scale_hardness')})

    return render(request, 'minerals/detail.html', {
        'header': header,
        'body': body,
        'mineral': mineral,
        'rand_pk': rand_mineral()
    })

minerals/templates/minerals/detail.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

{% block title %}{{ mineral.name }}{% endblock %}

{% block content %}
    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ header.name }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'minerals/img' %}/{{ header.name }}.jpg" alt="{{ header.name|title }}">
        <p class="mineral__caption">{{ header.image_caption }}</p>
      </div>
      <div class="mineral__table-container">
        <table class="mineral__table">
            {% for field, value in body.items %}
                {% if value %}
                <tr>
                    <td class="mineral__category">{{ field|title }}</td>
                    {% if field == 'formula' %}
                        <td class="mineral__formula">{{ value|safe }}
                    {% else %}
                        <td>{{ value|safe }}</td>
                    {% endif %}
                </tr>
                {% endif %}
            {% endfor %}
            {% for field, value in mineral.items %}
                {% if value %}
                <tr>
                    <td class="mineral__category">{{ field|title }}</td>
                   <td>{{ value|safe }}</td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
      </div>
    </div>
{% endblock %}

{% block rand_mineral %}
    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals:detail' pk=rand_pk %}">Show random mineral</a>
    </div>
{% endblock %}

minerals/templates/minerals/index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="grid-100">
      <ul class="minerals__container">
          {% for mineral in minerals %}
            <li class="minerals__item">
                <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name|truncatewords:1 }}</a>
            </li>
          {% endfor %}
      </ul>
    </div>
{% endblock %}

{% block rand_mineral %}
    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals:detail' pk=rand_pk %}">Show random mineral</a>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>{% block title %}Macky's Minerals: A magnificant catalog of minerals{% endblock %}</title>

  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds bounds--small">
    <div class="grid-100">
      <a href="{% url 'minerals:list' %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    {% block content %}{% endblock %}
  </div>

  {% block rand_mineral %}{% endblock %}

</body>
</html>